### ISSUE TITLE
this package works with React-Native?

### ISSUE THREAD

**Issue by Nits7029** [VirgilSecurity/virgil-sdk-javascript#42]

**Comment by Nits7029** [comment]
i really like to encrypt my data in a react-native app if it works, thanks

**Comment by vadimavdeev** [comment]
Yes, this package works with react-native. The only thing you can't use in react-native is the `PrivateKeyStorage` class, because it uses IndexedDB, which is not available. But you don't have to use it. You can implement your own storage for private keys using [SecureStore](https://docs.expo.io/versions/v31.0.0/sdk/securestore) from Expo, OR [react-native-keychain](https://github.com/oblador/react-native-keychain) if you are using native code.

**Comment by radcheb** [comment]
Hi @vadimavdeev, we are testing a HIPAA-COMPLIANT chat app using virgil-sdk. I tried to adapt the [demo-firebase-js](https://github.com/VirgilSecurity/demo-firebase-js) for react-native (with expo) but I got this error: Error: Cannot use IndexedDbStorageAdapter. indexedDb is not supported. I thought this is the best place to ask this question.

**Comment by vadimavdeev** [comment]
Hi! You can use this project in react-native app, except that you can't use the `PrivateKeyStorage` class because it uses IndexedDb. We have created a [separate package](https://github.com/VirgilSecurity/virgil-key-storage-rn) for private key storage specifically for react-native. Check out the example in README. As for the demo-firebase-js, it uses a different package called [e3kit](https://github.com/VirgilSecurity/virgil-e3kit-js), which is not compatible with react-native as of this moment. We're working on making it compatible and planning to release a new version this week.

**Comment by xlewkanx** [comment]
Hi, @radcheb
Grab new 0.3.5 version of E3kit with React Native support
https://github.com/VirgilSecurity/virgil-e3kit-js#react-native-usage
Also here you can find the example of using with native modules, but you need to use  `import createExpoKeyEntryStorage from '@virgilsecurity/key-storage-rn/expo';` for react native with expo:
https://github.com/VirgilSecurity/virgil-e3kit-js/tree/master/example/E3kitReactNative

**Comment by spewarren** [comment]
> Hi @vadimavdeev, we are testing a HIPAA-COMPLIANT chat app using virgil-sdk. I tried to adapt the [demo-firebase-js](https://github.com/VirgilSecurity/demo-firebase-js) for react-native (with expo) but I got this error: Error: Cannot use IndexedDbStorageAdapter. indexedDb is not supported. I thought this is the best place to ask this question.

@radcheb Hello! Did you get e2ee working with Expo? I had to eject to get anything to work
