### ISSUE TITLE
 [TypeError: `renewJwtFn` must be a function]

### ISSUE THREAD

**Issue by yiytan92** [VirgilSecurity/virgil-sdk-javascript#46]
I'm gtting this error when I call EThree.initialize(Promise.resolve(virgilResponse.virgilToken) can anybody clarify the error?

**Comment by vadimavdeev** [comment]
Hi! You're passing a `Promise` into the `EThree.initialize`, but it expects a function that returns a `Promise`. It will call that function automatically whenever it needs a fresh access token for Virgil Cloud. I'm not sure how you get the `virgilResponse` object, but the easiest way to fix the error would be to just wrap the `Promise.resolve(virgilResponse.virgilToken)` in a function, like this:
```
EThree.initialize(() => Promise.resolve(virgilResponse.virgilToken))
```
The right way, however, would be to wrap the code that fetches the `virgilResponse` in a function and pass that function into `EThree.initialize`, so that it actually fetches the new token when needed.

That being said, this issue has nothing to do with this package. It's about the `e3kit` package which has its own GitHub repository you can post issues to - https://github.com/VirgilSecurity/virgil-e3kit-js
If you have any further issues with using e3kit, please post them there.

**Comment by yiytan92** [comment]
thank u
