### ISSUE TITLE
[React Native][6.0.0-alpha.1] "Error: Wrong JWT format" with CachingJwtProvider

### ISSUE THREAD

**Issue by paolospag** [VirgilSecurity/virgil-sdk-javascript#56]
I created a `getToken` function that return a Firebase JWT after authentication.

```jsx
firebase.auth().onAuthStateChanged(user => {
  ...
  const getToken = () user.getIdToken();
  ...
});
```

When I invoke an instance of `CachingJwtProvider` passing the function mentioned above, I get  `Error: Wrong JWT format` but I don’t understand why.

My JWT token seems to be well formatted and everything worked before moving from version `5.3.0` to `6.0.0-alpha.1`.

I would like to rollback to the previous version, but I don't know if it is incompatible with `@virgilsecurity/key-storage-rn@0.2.0-alpha.0`

Here I report the complete error:
```
Error: Wrong JWT format
    at new Jwt (virgil-sdk.browser.cjs.js:319)
    at Function.Jwt.fromString (virgil-sdk.browser.cjs.js:351)
    at virgil-sdk.browser.cjs.js:559
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:289
    at _callTimer (JSTimers.js:146)
    at _callImmediatesPass (JSTimers.js:194)
    at Object.callImmediates (JSTimers.js:458)
    at MessageQueue.__callImmediates (MessageQueue.js:366)
```

If you need more information, trying to handle the error I get `InvalidCharacterError`.
Something happen in this block:
```jsx
try {
  this.header = JSON.parse(base64UrlDecode(parts[0]));
  this.body = JSON.parse(base64UrlDecode(parts[1]));
  his.signature = base64UrlToBase64(parts[2]);
}
catch (e) {
  throw new Error('Wrong JWT format');
}
```
especially when trying to decode the body.

My configuration:
```json
"@virgilsecurity/key-storage-rn": "^0.2.0-alpha.0",
"react-native": "0.60.5",
"react-native-virgil-crypto": "0.3.0",
"virgil-sdk": "^6.0.0-alpha.1"
```

**Comment by vadimavdeev** [comment]
You need to return the Virgil JWT from that function, not the one from Firebase. You need to create a Firebase Function that will generate Virgil JWTs for your users. [Here's](https://github.com/VirgilSecurity/virgil-e3kit-firebase-func) a sample to get you started. Once that function is deployed, you'll need to modify your `getToken` function to make requests to it. See [this tutorial](https://developer.virgilsecurity.com/docs/use-cases/v5/encrypted-communication-for-firebase#initialize-e3kit) for a complete example.

**Comment by paolospag** [comment]
@vadimavdeev 
oh, it's curios...
I don't understand why in 5.3.0 Firebase JWT works fine, I haven't had any problems before...
So, is it safe to stay on 5.3.0 or can I use the [Virgil JWT Generator](https://github.com/VirgilSecurity/virgil-e3kit-firebase-func/blob/master/functions/src/generate-virgil-jwt.ts#L9-L14) as standalone (so without passing any api key)?

**Comment by vadimavdeev** [comment]
There's a bug in JWT parsing in v6.0.0. We'll fix it asap. However, Firebase JWT, even if it had been parsed successfully before, would have been rejected by the Virgil Cloud anyway so I don't know how it worked unless you weren't making any API calls to Virgil Cloud.

Yes, it is safe to stay on v5.3.0. No, you cannot use the Virgil JWT Generator without passing an API key. However, given that the API Key is just like the normal key you create with `virgilCrypto.generateKeys()`, you can generate one and use it if you're not planning to make any API calls (because JWTs signed with such a key would be rejected by the Cloud).

**Comment by paolospag** [comment]
> There's a bug in JWT parsing in v6.0.0. We'll fix it asap.

So, this bug doesn't parse any type of JWT, correct?
I noticed this [pull request](https://github.com/VirgilSecurity/virgil-sdk-javascript/pull/57), can I upgrade to `6.0.0-alpha.2`?

> However, Firebase JWT, even if it had been parsed successfully before, would have been rejected by the Virgil Cloud anyway so I don't know how it worked unless you weren't making any API calls to Virgil Cloud.

Exactly, I don't make any call to Virgil Cloud... I'm just using an instance of `CachingJwtProvider` to check JWT expiration when my custom implementation of `EThree` class is initialized.

> Yes, it is safe to stay on v5.3.0.

But I get these warnings:
```
@virgilsecurity/key-storage-rn@0.2.0 requires a peer of virgil-sdk@next but none is installed. You must install peer dependencies yourself.

virgil-sdk@5.3.0 requires a peer of virgil-crypto@3.x but none is installed. You must install peer dependencies yourself.
```

**Comment by vadimavdeev** [comment]
> So, this bug doesn't parse any type of JWT, correct?

Technically, it can parse _some_ JWTs, but you can think of it that way.

> I noticed this pull request, can I upgrade to 6.0.0-alpha.2?

Once it's merged, you can upgrade. The 6.0.0-alpha.2 version is not in NPM yet.

> Exactly, I don't make any call to Virgil Cloud... I'm just using an instance of CachingJwtProvider to check JWT expiration when my custom implementation of EThree class is initialized.

Why do you care whether the JWT has expired if you don't make any API calls?

> But I get these warnings:

You'll need to downgrade the `@virgilsecurity/key-storage-rn` to version v0.1.3 to stay on virgil-sdk@5.3.0. And you can ignore the `virgil-crypto` warning because 1) It's backward-compatible wit h previous version (except for the password-protected import \ export of private keys, which will be fixed soon) and 2) I believe you use the `react-native-virgil-crypto`
