### ISSUE TITLE
Webpack 5

### ISSUE THREAD

**Issue by edwinckc** [VirgilSecurity/virgil-sdk-javascript#89]
Hello, are there any plans to upgrade to Webpack 5?

Webpack 4 is starting to come with more dependency security issues, and it looks like they don't plan to fix them because they will be breaking changes. The recommended action is always to upgrade to Webpack 5 unfortunately.  I am seeing two dependabot alerts for `set-value` and `glob-parent`, and it looks like both can be traced back to Webpack 4 which is required by `virgil-sdk`.

https://github.com/webpack/webpack/issues/12286
https://github.com/webpack/webpack/pull/12319

Thanks, cheers 🍺

**Comment by chinesehemp** [comment]
Dito. I'm trying to use Virgil with NextJS, which is using Webpack 5, and I'm having trouble with the enhanced-resolve package dependency from Webpack 4, causing an error when I try to deploy to firebase. This issue is well over 1 year old. Any plans to bring support for Webpack 5?

**Comment by chinesehemp** [comment]
Any chance of getting Webpack 5 support? I'm using NextJS 12.3.1, which uses Webpack 5 as the bundler. The `next-transpile-modules` is causing a compatibility issue when deploying to production because it's using `enhanced-resolve@5.10.0` and `@virgilsecurity/e3kit-browser` using webpack 4, which has a dependency on `enhanced-resolve@4.5.0`. I've tried using webpack 5 new Asset Modules asset/resource loader instead of file-loader, which doesn't pick up the wasm. Getting the following error...

```
wait  - compiling /channel/[cid]...
error - ./node_modules/@virgilsecurity/e3kit-browser/browser.es.js:2:0
Module not found: Can't resolve 'asset/resource'
```

Here is my next.config.js for ref

```
/** @type {import('next').NextConfig} */

const path = require("path");

const withTM = require("next-transpile-modules")([
  "@virgilsecurity/e3kit-browser",
  "virgil-crypto",
  "@virgilsecurity/pythia-crypto",
]);

const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  sassOptions: {
    includePaths: [path.join(__dirname, "styles")],
  },
  compiler: {
    removeConsole: {
      exclude: ["error"],
    },
  },
  async rewrites() {
    return [
      {
        source: "/@:username",
        destination: "/:username",
      },
    ];
  },
  webpack: (config) => {
    config.experiments = {
      asyncWebAssembly: true,
      syncWebAssembly: true,
    };
    config.module.rules[
      config.module.rules.findIndex((rule) => rule.oneOf)
    ].oneOf.unshift({
      test: /\.wasm$/,
      loader: "asset/resource",
      options: {
        outputPath: "static/wasm/",
      },
    });

    return config;
  },
};

module.exports = withTM(nextConfig);
```

When I try to build it using the file-loader from Webpack 4, I get the following error when I try to deploy to my server.

```
✘ [ERROR] Could not resolve "pnpapi"

    node_modules/enhanced-resolve/lib/ResolverFactory.js:126:17:
      126 │     return require("pnpapi"); // eslint-disable-line node/no-missing-require
          ╵                    ~~~~~~~~
```

At this point, I've got no alternative except to ditch NextJS and go with vanilla CRA.

**Comment by Scratch-net** [comment]
The support for Webpack 5 is coming next week or so, stay tuned
